Python 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> dna = 'CGGAGTGTCATGAGACACACGGATGGGTTAGAGTATGGACATCTGTGACTTCAACGTGTATGCATATATGATTTACATCCGGGCACAGATGTGCCTTTCCTCTGAGGCCCAGCACCACATGCGCACGGTAGTTTCATTGAATCGGCCGAACAAGACGAGATCCGCTCACATTTTAAGCTTCGCTATTATACGAAGCTGGAACCGCGTCTCGCTCGGTCACGCTCGAATCCACGGAATCCTCGAGCAAAAATGCTAAATAGAGCATAGACAGGTTAGTACGGTCTCGGCCCTACATCCACTTTTCTACGAGTATGTCGGTGATAAACTTGACTGCACATTCGACTATCGCCCTTAAACACGCAGAGGGGTCAGCCTGTGAAGGAAACCCTAGGGGAGCTTGGTACGACCCAGTGGTTGATGCGTCCTCTACCGCCCTACTGTACTGATGAGGGTCTGACTTCTCTCAGGCTCGAAGCGAGTCTTCCAGTTTGCCGTATAACAACCCTCAAGTGCATGGGCGACGGATCTAGTTCGAGCGCTCTGACGCTGAAAGTCGTGCTTATAGCATTCGTATCGGTGGGTTAGGTTAGCTCGTGAATGTTATTTTTATCCCATGCGTACTCACGCGGAGGTCACAGGAAGCGCCTATGCTTGCTCGGAACTGTTTTTTTTTTGTCTAGGTACTGCTGGGGACGACACTATTCCACACCGCTCCTCCGGTTTCCCACCACGGTATTGAGACTTCCATCCCGTTCGAGAACGGACTGCACAACTGGATCACCCACACTAACGGTCATATAATTACGTTACATTATCTCTCTCTTTAACTTGGACGCGTGCCGTTACTACGACCTTTCATCGCGAGTGCGTACTGAGACGGGACTGGGCATAAATCCTCCAGACCCAGAGAGCGTCTTGACTGGCACCTACCACGGCAGTGCCGCAAAATTATAACCACCAAATTGCACGGC'
>>> 
>>> a = dna.count('A')
>>> c = dna.count('C')
>>> g = dna.count('G')
>>> t = dna.count('T')
>>> 
>>> print(f"{a} {c} {g} {t}")
230 260 234 247
